### ISSUE TITLE
More ways to deploy

### ISSUE THREAD

**Issue by jimender2** [iteratec/juicy-ctf#22]
I am trying to set juicy-ctf up using a local on premise ubuntu server.  Could there be some sort of instructions on how to set this up on pure ubuntu and use just one computer (virtualization or two docker instances perhaps)

This would probably need to include instructions on how to install kubernetes and helm to fit this method the best.

Also, as a possibility, if a docker image was added as a deployment method, that would be nice also. (have docker as a wrapper so that everything is contained inside)

**Comment by bkimminich** [comment]
JuicyCTF is explicitly for Kubernetes environments. For single servers where you want to launch multiple Juice Shop instances the recommendation is to launch those on different ports an assign them to training or CTF participants, e.g. with

```
for i in {10..19}; do docker run -d -p 40$i:3000 bkimminich/juice-shop; done 
```

**Comment by J12934** [comment]
Hi @jimender2 
Björn already summed it up quite nicely, just one thing.
Even thought JuicyCTF is currently only compatible with kubernetes, it should be possible to also add compatibility with other orchestrators, (`docker swarm` or just with raw docker containers or maybe even with native processes) as the projects really only needs the possibility to spin up new JuiceShop instances at a stable network address, so that the loadbalancer can direct traffic to the instances reliably.

This would require some work but would very much be possibly. 
I don't think that i will implement this myself as I'm pretty happy with the kubernetes solution for myself and it works great for the usecases we use it @iteratec.

As to documentation on how to do set it up with kubernetes on a bare Ubuntu server I'm unfortunately not really an expert at either as I'm mostly using k8s clusters managed by cloud providers. If you could write up a guide to your experiences on how to set it up that would be really cool! Would happily merge a guide or link to one!

**Comment by J12934** [comment]
Closing as the question seems answered.
If you got more questions, feel free to open up another issue or pinging us in slack 👍
